name: Build Windows EXE
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - name: Build Windows EXE
        run: go build -o fuelhack.exe examples/fuelhack/
      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: simconnect-go